In [1]:
import numpy as np
import pandas as pd
import pickle

## 실습 내용

## 1. Jupyter notebook basic
자주 사용 하는 단축키들


##  주석 1

In [2]:
# esc: command mode
# entder: edit mode
# h: help

# Command mode
# a: 위에 셀 추가
# b: 아래 셀 추가
# o: 결과창 숨기기

# edit mode
# ctrl + shift + - : 현재 기준으로 셀 나누기

# cell type
# m: markdown
# c: cell

## 2. Pandas

### 2.1 파일 불러들이기

In [3]:
#jupyter notebook 상에서 library 설치
!pip install xlrd

You should consider upgrading via the 'c:\users\smarthinj\anaconda3\envs\smarthinj\python.exe -m pip install --upgrade pip' command.


In [4]:
df = pd.read_csv('./Dataset/dataset_city.csv')

In [5]:
type(df) #EQ의 자료형 확인

pandas.core.frame.DataFrame

In [6]:
# ctrl + enter: 현재 셀만 실행
# alt + enter : 현재 셀 실행 후 아래에 새로운 셀 추가
# shift + enter : 현재 셀 실행 후 아래 셀로 이동

In [7]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

### 2.2 pandas dataframe 살펴보기

In [14]:
?df.head

In [15]:
df.head(5) #처음 5개 row 살펴보기

col1             col2  col3  col4  col5   col6   col7  col8  col9  \
0  Ahmedabad  2015-01-01 1:00   NaN   NaN  1.00  40.01  36.37   NaN  1.00   
1  Ahmedabad  2015-01-01 2:00   NaN   NaN  0.02  27.75  19.73   NaN  0.02   
2  Ahmedabad  2015-01-01 3:00   NaN   NaN  0.08  19.32  11.08   NaN  0.08   
3  Ahmedabad  2015-01-01 4:00   NaN   NaN  0.30  16.45   9.20   NaN  0.30   
4  Ahmedabad  2015-01-01 5:00   NaN   NaN  0.12  14.90   7.85   NaN  0.12   

    col10   col11  col12  col13  col14  col15 col16  
0  122.07     NaN    0.0    0.0    0.0    NaN   NaN  
1   85.90     NaN    0.0    0.0    0.0    NaN   NaN  
2   52.83     NaN    0.0    0.0    0.0    NaN   NaN  
3   39.53  153.58    0.0    0.0    0.0    NaN   NaN  
4   32.63     NaN    0.0    0.0    0.0    NaN   NaN

In [16]:
df['col2']

0          2015-01-01 1:00
1          2015-01-01 2:00
2          2015-01-01 3:00
3          2015-01-01 4:00
4          2015-01-01 5:00
                ...       
670825    2020-06-30 20:00
670826    2020-06-30 21:00
670827    2020-06-30 22:00
670828    2020-06-30 23:00
670829     2020-07-01 0:00
Name: col2, Length: 670830, dtype: object

In [17]:
# loc: label을 이용하여 접근
df.loc[0:2,'col3':'col6']

col3  col4  col5   col6
0   NaN   NaN  1.00  40.01
1   NaN   NaN  0.02  27.75
2   NaN   NaN  0.08  19.32

In [18]:
df.loc[:5,:'col4']

col1             col2  col3  col4
0  Ahmedabad  2015-01-01 1:00   NaN   NaN
1  Ahmedabad  2015-01-01 2:00   NaN   NaN
2  Ahmedabad  2015-01-01 3:00   NaN   NaN
3  Ahmedabad  2015-01-01 4:00   NaN   NaN
4  Ahmedabad  2015-01-01 5:00   NaN   NaN
5  Ahmedabad  2015-01-01 6:00   NaN   NaN

In [19]:
df.loc[:,'col2':'col3']

col2   col3
0        2015-01-01 1:00    NaN
1        2015-01-01 2:00    NaN
2        2015-01-01 3:00    NaN
3        2015-01-01 4:00    NaN
4        2015-01-01 5:00    NaN
...                  ...    ...
670825  2020-06-30 20:00   9.50
670826  2020-06-30 21:00  17.25
670827  2020-06-30 22:00  36.00
670828  2020-06-30 23:00  15.75
670829   2020-07-01 0:00  15.00

[670830 rows x 2 columns]

In [20]:
# iloc: 위치 정수를 통한 접근
df.iloc[:2,:]

col1             col2  col3  col4  col5   col6   col7  col8  col9  \
0  Ahmedabad  2015-01-01 1:00   NaN   NaN  1.00  40.01  36.37   NaN  1.00   
1  Ahmedabad  2015-01-01 2:00   NaN   NaN  0.02  27.75  19.73   NaN  0.02   

    col10  col11  col12  col13  col14  col15 col16  
0  122.07    NaN    0.0    0.0    0.0    NaN   NaN  
1   85.90    NaN    0.0    0.0    0.0    NaN   NaN

In [21]:
df.iloc[2:4,1:4]

col2  col3  col4
2  2015-01-01 3:00   NaN   NaN
3  2015-01-01 4:00   NaN   NaN

In [22]:
df.iloc[:5,:2]

col1             col2
0  Ahmedabad  2015-01-01 1:00
1  Ahmedabad  2015-01-01 2:00
2  Ahmedabad  2015-01-01 3:00
3  Ahmedabad  2015-01-01 4:00
4  Ahmedabad  2015-01-01 5:00

In [23]:
#  변수 형태 살펴보기
df.dtypes

col1      object
col2      object
col3     float64
col4     float64
col5     float64
col6     float64
col7     float64
col8     float64
col9     float64
col10    float64
col11    float64
col12    float64
col13    float64
col14    float64
col15    float64
col16     object
dtype: object

In [24]:
# 요약
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670830 entries, 0 to 670829
Data columns (total 16 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   col1    670830 non-null  object 
 1   col2    670830 non-null  object 
 2   col3    530858 non-null  float64
 3   col4    380931 non-null  float64
 4   col5    558625 non-null  float64
 5   col6    557935 non-null  float64
 6   col7    551494 non-null  float64
 7   col8    407200 non-null  float64
 8   col9    586398 non-null  float64
 9   col10   543891 non-null  float64
 10  col11   547372 non-null  float64
 11  col12   515584 non-null  float64
 12  col13   460298 non-null  float64
 13  col14   243501 non-null  float64
 14  col15   545725 non-null  float64
 15  col16   545725 non-null  object 
dtypes: float64(13), object(3)
memory usage: 81.9+ MB


In [25]:
df.describe()

col3           col4           col5           col6  \
count  530858.000000  380931.000000  558625.000000  557935.000000   
mean       70.067364     124.037024      17.813423      29.589279   
std        76.084568     105.663468      32.702488      29.593462   
min         0.010000       0.010000       0.010000       0.010000   
25%        27.750000      56.610000       3.900000      11.110000   
50%        48.500000      94.890000       8.080000      21.000000   
75%        82.250000     153.100000      16.450000      37.220000   
max       999.990000    1000.000000     499.990000     499.510000   

                col7           col8           col9          col10  \
count  551494.000000  407200.000000  586398.000000  543891.000000   
mean       32.957969      24.268378       2.265773      14.312244   
std        40.536889      29.545867      11.286639      19.788800   
min         0.000000       0.010000       0.000000       0.010000   
25%        10.720000       8.310000       0.420000       4.800000   
50%        21.240000      15.900000       0.810000       8.400000   
75%        37.930000      29.930000       1.380000      15.100000   
max       498.610000     499.970000     498.570000     199.960000   

               col11          col12          col13          col14  \
count  547372.000000  515584.000000  460298.000000  243501.000000   
mean       34.807954       3.127310       8.923422       3.146776   
std        29.930581      16.525254      21.948098       7.944772   
min         0.010000       0.000000       0.000000       0.000000   
25%        13.280000       0.080000       0.470000       0.090000   
50%        26.180000       0.920000       2.770000       0.780000   
75%        47.680000       2.830000       8.750000       3.120000   
max       497.620000     498.070000     499.400000     499.990000   

               col15  
count  545725.000000  
mean      171.587336  
std       165.261902  
min         9.000000  
25%        81.000000  
50%       120.000000  
75%       217.000000  
max      3133.000000

In [26]:
df['col3'].mean()

70.06736366410603

In [27]:
df['col3'].std()

76.08456799269976

### 2.3 특정 조건에 행이나 열 선택하기

In [28]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [29]:
# 열 'D4'가 13인 것들만 선택하기
idx1 = df['col5']>=1
print(idx1)

0          True
1         False
2         False
3         False
4         False
          ...  
670825     True
670826     True
670827     True
670828     True
670829    False
Name: col5, Length: 670830, dtype: bool


In [30]:
df[idx1]

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
7           Ahmedabad   2015-01-01 8:00    NaN    NaN  1.03  16.66  16.48   
8           Ahmedabad   2015-01-01 9:00    NaN    NaN  1.47  16.25  18.02   
9           Ahmedabad  2015-01-01 10:00    NaN    NaN  2.05  13.78  16.08   
10          Ahmedabad  2015-01-01 11:00    NaN    NaN  2.27  13.87  16.73   
...               ...               ...    ...    ...   ...    ...    ...   
670823  Visakhapatnam  2020-06-30 18:00   6.50  24.75  2.25  23.38  13.68   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   

         col8  col9   col10   col11  col12  col13  col14  col15         col16  
0         NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
7         NaN  1.03   20.92  177.21    0.0    0.0    0.0    NaN           NaN  
8         NaN  1.47   16.45  122.08    0.0    0.0    0.0    NaN           NaN  
9         NaN  2.05   15.14     NaN    0.0    0.0    0.0    NaN           NaN  
10        NaN  2.27   14.12   99.17    0.0    0.0    0.0    NaN           NaN  
...       ...   ...     ...     ...    ...    ...    ...    ...           ...  
670823  10.60  0.66    5.80   33.55    NaN    NaN    NaN   51.0  Satisfactory  
670825   4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826   3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827   3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828   3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  

[538713 rows x 16 columns]

In [31]:
idx2 = (df['col5']>=1 ) & (df['col9']<=0.5)
df[idx2]

col1              col2   col3    col4   col5   col6   col7  \
46224       Ahmedabad   2020-04-10 1:00  68.81  136.03   5.23  39.01  22.93   
46225       Ahmedabad   2020-04-10 2:00  60.53  124.78   3.83  22.58  13.87   
46226       Ahmedabad   2020-04-10 3:00  43.08  105.17   3.94  17.66  11.55   
46227       Ahmedabad   2020-04-10 4:00  35.20   90.28   5.67  24.95  16.41   
46231       Ahmedabad   2020-04-10 8:00  23.55   63.03   8.29  18.92  15.42   
...               ...               ...    ...     ...    ...    ...    ...   
670810  Visakhapatnam   2020-06-30 5:00  13.50   44.75   6.60  35.15  24.05   
670811  Visakhapatnam   2020-06-30 6:00  15.00   50.00  15.45  36.88  32.20   
670819  Visakhapatnam  2020-06-30 14:00  10.75   36.75   1.10  17.75  10.28   
670821  Visakhapatnam  2020-06-30 16:00  14.00   29.50   1.77  20.70  12.45   
670828  Visakhapatnam  2020-06-30 23:00  15.75   63.00   1.02  28.90  16.00   

        col8  col9  col10  col11  col12   col13  col14  col15         col16  
46224    NaN  0.27  44.82  11.11  22.46  105.65   8.73  127.0      Moderate  
46225    NaN  0.19  67.26   9.76  10.52  100.23   5.00  127.0      Moderate  
46226    NaN  0.18  42.30   9.79   5.09   36.42   2.94  127.0      Moderate  
46227    NaN  0.42  57.69   9.99   3.87   22.38   1.90  127.0      Moderate  
46231    NaN  0.38  11.57   9.76   2.20   15.42   1.82   94.0  Satisfactory  
...      ...   ...    ...    ...    ...     ...    ...    ...           ...  
670810  7.90  0.23   7.95  23.35   0.00    0.00   0.00   55.0  Satisfactory  
670811  5.92  0.35   3.60  14.62   0.00    0.00   0.00   54.0  Satisfactory  
670819  4.65  0.34   4.38  50.73   0.00    0.00   0.00   51.0  Satisfactory  
670821  8.08  0.45   7.12  39.23   0.00    0.00   0.00   51.0  Satisfactory  
670828  3.80  0.49   0.75  15.82    NaN     NaN    NaN   50.0          Good  

[125096 rows x 16 columns]

In [32]:
idx3 = (df['col5']>=1 ) |(df['col9']<=0.5)
df[idx3]

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670824  Visakhapatnam  2020-06-30 19:00   8.25  33.25  0.35  24.05  13.05   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670824  5.55  0.44    1.85   41.38    NaN    NaN    NaN   51.0  Satisfactory  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  

[589463 rows x 16 columns]

In [33]:
df.dtypes

col1      object
col2      object
col3     float64
col4     float64
col5     float64
col6     float64
col7     float64
col8     float64
col9     float64
col10    float64
col11    float64
col12    float64
col13    float64
col14    float64
col15    float64
col16     object
dtype: object

In [34]:
# 변수 형태가 object (문자열 포함)인 열만 선택하기
idx4 = df.dtypes=='object'
print(idx4)

col1      True
col2      True
col3     False
col4     False
col5     False
col6     False
col7     False
col8     False
col9     False
col10    False
col11    False
col12    False
col13    False
col14    False
col15    False
col16     True
dtype: bool


In [37]:
df.loc[:,idx4]

col1              col2         col16
0           Ahmedabad   2015-01-01 1:00           NaN
1           Ahmedabad   2015-01-01 2:00           NaN
2           Ahmedabad   2015-01-01 3:00           NaN
3           Ahmedabad   2015-01-01 4:00           NaN
4           Ahmedabad   2015-01-01 5:00           NaN
...               ...               ...           ...
670825  Visakhapatnam  2020-06-30 20:00  Satisfactory
670826  Visakhapatnam  2020-06-30 21:00  Satisfactory
670827  Visakhapatnam  2020-06-30 22:00          Good
670828  Visakhapatnam  2020-06-30 23:00          Good
670829  Visakhapatnam   2020-07-01 0:00          Good

[670830 rows x 3 columns]

In [38]:
df.describe()

col3           col4           col5           col6  \
count  530858.000000  380931.000000  558625.000000  557935.000000   
mean       70.067364     124.037024      17.813423      29.589279   
std        76.084568     105.663468      32.702488      29.593462   
min         0.010000       0.010000       0.010000       0.010000   
25%        27.750000      56.610000       3.900000      11.110000   
50%        48.500000      94.890000       8.080000      21.000000   
75%        82.250000     153.100000      16.450000      37.220000   
max       999.990000    1000.000000     499.990000     499.510000   

                col7           col8           col9          col10  \
count  551494.000000  407200.000000  586398.000000  543891.000000   
mean       32.957969      24.268378       2.265773      14.312244   
std        40.536889      29.545867      11.286639      19.788800   
min         0.000000       0.010000       0.000000       0.010000   
25%        10.720000       8.310000       0.420000       4.800000   
50%        21.240000      15.900000       0.810000       8.400000   
75%        37.930000      29.930000       1.380000      15.100000   
max       498.610000     499.970000     498.570000     199.960000   

               col11          col12          col13          col14  \
count  547372.000000  515584.000000  460298.000000  243501.000000   
mean       34.807954       3.127310       8.923422       3.146776   
std        29.930581      16.525254      21.948098       7.944772   
min         0.010000       0.000000       0.000000       0.000000   
25%        13.280000       0.080000       0.470000       0.090000   
50%        26.180000       0.920000       2.770000       0.780000   
75%        47.680000       2.830000       8.750000       3.120000   
max       497.620000     498.070000     499.400000     499.990000   

               col15  
count  545725.000000  
mean      171.587336  
std       165.261902  
min         9.000000  
25%        81.000000  
50%       120.000000  
75%       217.000000  
max      3133.000000

#### 실습
* 열 조건: 형태가 숫자형

* 행 조건: 3열의 값이 평균 이상

> 예: 'col3'>= df['col3'].mean()

* 두 조건을 만족하는 데이터만 filter하기

In [39]:
idx_col = (df.dtypes=='float') | (df.dtypes=='int64')
idx_row = (df['col3']>=df['col3'].mean())

In [41]:
print(df.iloc[idx_row.array,idx_col.array])

          col3    col4   col5   col6    col7   col8   col9  col10  col11  \
668      81.30     NaN  23.23  47.66   75.67    NaN  23.23  50.19  30.83   
669     105.53     NaN  43.73  45.93   94.58    NaN  43.73  31.99  53.83   
670     118.33     NaN  39.17  43.69   87.27    NaN  39.17  44.06  42.88   
671     119.40     NaN  61.20  42.79  107.30    NaN  61.20  20.02  12.62   
672     137.43     NaN  11.02  41.19   52.90    NaN  11.02  38.24  28.25   
...        ...     ...    ...    ...     ...    ...    ...    ...    ...   
670382   71.00  143.00  26.22  60.15   53.30   9.25   1.11   1.40  18.48   
670629   83.75  181.75   0.90  36.45   19.75  19.65   0.93  25.62  68.60   
670677  126.50  185.50   2.77  33.22   19.93  26.65   1.52  17.98  28.48   
670678  169.50  235.75   2.23  30.95   18.30  24.15   1.29  14.80  28.57   
670679  107.75  161.50   1.82  21.62   12.53  16.45   0.54    NaN  28.80   

        col12  col13  col14  col15  
668      0.27   0.00   5.82    NaN  
669      0.00

In [42]:
# 두 pandas dataframe 합치기

df1 = df.loc[:,('col2','col4')]
df2 = df.loc[:,('col1','col3')]

In [43]:
df3 = pd.concat([df1,df2],axis=1)

In [44]:
df3

col2   col4           col1   col3
0        2015-01-01 1:00    NaN      Ahmedabad    NaN
1        2015-01-01 2:00    NaN      Ahmedabad    NaN
2        2015-01-01 3:00    NaN      Ahmedabad    NaN
3        2015-01-01 4:00    NaN      Ahmedabad    NaN
4        2015-01-01 5:00    NaN      Ahmedabad    NaN
...                  ...    ...            ...    ...
670825  2020-06-30 20:00  36.00  Visakhapatnam   9.50
670826  2020-06-30 21:00  49.25  Visakhapatnam  17.25
670827  2020-06-30 22:00  71.00  Visakhapatnam  36.00
670828  2020-06-30 23:00  63.00  Visakhapatnam  15.75
670829   2020-07-01 0:00  66.00  Visakhapatnam  15.00

[670830 rows x 4 columns]

### 2.4 결측치 처리 하기

In [45]:
df.head()

col1             col2  col3  col4  col5   col6   col7  col8  col9  \
0  Ahmedabad  2015-01-01 1:00   NaN   NaN  1.00  40.01  36.37   NaN  1.00   
1  Ahmedabad  2015-01-01 2:00   NaN   NaN  0.02  27.75  19.73   NaN  0.02   
2  Ahmedabad  2015-01-01 3:00   NaN   NaN  0.08  19.32  11.08   NaN  0.08   
3  Ahmedabad  2015-01-01 4:00   NaN   NaN  0.30  16.45   9.20   NaN  0.30   
4  Ahmedabad  2015-01-01 5:00   NaN   NaN  0.12  14.90   7.85   NaN  0.12   

    col10   col11  col12  col13  col14  col15 col16  
0  122.07     NaN    0.0    0.0    0.0    NaN   NaN  
1   85.90     NaN    0.0    0.0    0.0    NaN   NaN  
2   52.83     NaN    0.0    0.0    0.0    NaN   NaN  
3   39.53  153.58    0.0    0.0    0.0    NaN   NaN  
4   32.63     NaN    0.0    0.0    0.0    NaN   NaN

In [46]:
# nan이면 true 아니면 false
df.isnull()

col1   col2   col3   col4   col5   col6   col7   col8   col9  col10  \
0       False  False   True   True  False  False  False   True  False  False   
1       False  False   True   True  False  False  False   True  False  False   
2       False  False   True   True  False  False  False   True  False  False   
3       False  False   True   True  False  False  False   True  False  False   
4       False  False   True   True  False  False  False   True  False  False   
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
670825  False  False  False  False  False  False  False  False  False   True   
670826  False  False  False  False  False  False  False  False  False  False   
670827  False  False  False  False  False  False  False  False  False  False   
670828  False  False  False  False  False  False  False  False  False  False   
670829  False  False  False  False  False  False  False  False  False  False   

        col11  col12  col13  col14  col15  col16  
0        True  False  False  False   True   True  
1        True  False  False  False   True   True  
2        True  False  False  False   True   True  
3       False  False  False  False   True   True  
4        True  False  False  False   True   True  
...       ...    ...    ...    ...    ...    ...  
670825  False   True   True   True  False  False  
670826  False   True   True   True  False  False  
670827  False   True   True   True  False  False  
670828  False   True   True   True  False  False  
670829  False   True   True   True  False  False  

[670830 rows x 16 columns]

In [47]:
# 각 행별 결측치 갯수
df.isnull().sum(1) 

0         6
1         6
2         6
3         5
4         6
         ..
670825    4
670826    3
670827    3
670828    3
670829    3
Length: 670830, dtype: int64

In [48]:
#각 열별 결측치 갯수
df.isnull().sum()

col1          0
col2          0
col3     139972
col4     289899
col5     112205
col6     112895
col7     119336
col8     263630
col9      84432
col10    126939
col11    123458
col12    155246
col13    210532
col14    427329
col15    125105
col16    125105
dtype: int64

In [49]:
idx5 = df.isnull().sum()<=200000
df.iloc[:,idx5.array]

col1              col2   col3  col5   col6   col7  col9  \
0           Ahmedabad   2015-01-01 1:00    NaN  1.00  40.01  36.37  1.00   
1           Ahmedabad   2015-01-01 2:00    NaN  0.02  27.75  19.73  0.02   
2           Ahmedabad   2015-01-01 3:00    NaN  0.08  19.32  11.08  0.08   
3           Ahmedabad   2015-01-01 4:00    NaN  0.30  16.45   9.20  0.30   
4           Ahmedabad   2015-01-01 5:00    NaN  0.12  14.90   7.85  0.12   
...               ...               ...    ...   ...    ...    ...   ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  2.75  25.57  15.85  0.62   
670826  Visakhapatnam  2020-06-30 21:00  17.25  3.62  33.20  20.62  0.76   
670827  Visakhapatnam  2020-06-30 22:00  36.00  2.20  30.80  18.20  0.58   
670828  Visakhapatnam  2020-06-30 23:00  15.75  1.02  28.90  16.00  0.49   
670829  Visakhapatnam   2020-07-01 0:00  15.00  0.40  26.85  14.05  0.59   

         col10   col11  col12  col15         col16  
0       122.07     NaN    0.0    NaN           NaN  
1        85.90     NaN    0.0    NaN           NaN  
2        52.83     NaN    0.0    NaN           NaN  
3        39.53  153.58    0.0    NaN           NaN  
4        32.63     NaN    0.0    NaN           NaN  
...        ...     ...    ...    ...           ...  
670825     NaN   27.75    NaN   51.0  Satisfactory  
670826    2.02   25.58    NaN   51.0  Satisfactory  
670827    1.77   26.15    NaN   50.0          Good  
670828    0.75   15.82    NaN   50.0          Good  
670829    2.10   17.05    NaN   50.0          Good  

[670830 rows x 12 columns]

In [50]:
# 결측치를 모두 0으로 채우기
df.fillna(0)

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00   0.00   0.00  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00   0.00   0.00  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00   0.00   0.00  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00   0.00   0.00  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00   0.00   0.00  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0       0.00  1.00  122.07    0.00    0.0    0.0    0.0    0.0             0  
1       0.00  0.02   85.90    0.00    0.0    0.0    0.0    0.0             0  
2       0.00  0.08   52.83    0.00    0.0    0.0    0.0    0.0             0  
3       0.00  0.30   39.53  153.58    0.0    0.0    0.0    0.0             0  
4       0.00  0.12   32.63    0.00    0.0    0.0    0.0    0.0             0  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62    0.00   27.75    0.0    0.0    0.0   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    0.0    0.0    0.0   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    0.0    0.0    0.0   50.0          Good  
670828  3.80  0.49    0.75   15.82    0.0    0.0    0.0   50.0          Good  
670829  5.20  0.59    2.10   17.05    0.0    0.0    0.0   50.0          Good  

[670830 rows x 16 columns]

In [51]:
df.fillna(1)

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00   1.00   1.00  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00   1.00   1.00  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00   1.00   1.00  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00   1.00   1.00  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00   1.00   1.00  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0       1.00  1.00  122.07    1.00    0.0    0.0    0.0    1.0             1  
1       1.00  0.02   85.90    1.00    0.0    0.0    0.0    1.0             1  
2       1.00  0.08   52.83    1.00    0.0    0.0    0.0    1.0             1  
3       1.00  0.30   39.53  153.58    0.0    0.0    0.0    1.0             1  
4       1.00  0.12   32.63    1.00    0.0    0.0    0.0    1.0             1  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62    1.00   27.75    1.0    1.0    1.0   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    1.0    1.0    1.0   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    1.0    1.0    1.0   50.0          Good  
670828  3.80  0.49    0.75   15.82    1.0    1.0    1.0   50.0          Good  
670829  5.20  0.59    2.10   17.05    1.0    1.0    1.0   50.0          Good  

[670830 rows x 16 columns]

In [52]:
values = {'col3': 0, 'col4': 1}
df.fillna(value=values)

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00   0.00   1.00  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00   0.00   1.00  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00   0.00   1.00  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00   0.00   1.00  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00   0.00   1.00  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [53]:
# 연속형 변수를 평균으로 채우기
idx_contin = df.dtypes=='float64'
df_contin=df.loc[:,idx_contin]
print(df_contin)
df_contin_fill = df_contin.fillna(df_contin.mean())
print(df_contin_fill)

         col3   col4  col5   col6   col7  col8  col9   col10   col11  col12  \
0         NaN    NaN  1.00  40.01  36.37   NaN  1.00  122.07     NaN    0.0   
1         NaN    NaN  0.02  27.75  19.73   NaN  0.02   85.90     NaN    0.0   
2         NaN    NaN  0.08  19.32  11.08   NaN  0.08   52.83     NaN    0.0   
3         NaN    NaN  0.30  16.45   9.20   NaN  0.30   39.53  153.58    0.0   
4         NaN    NaN  0.12  14.90   7.85   NaN  0.12   32.63     NaN    0.0   
...       ...    ...   ...    ...    ...   ...   ...     ...     ...    ...   
670825   9.50  36.00  2.75  25.57  15.85  4.57  0.62     NaN   27.75    NaN   
670826  17.25  49.25  3.62  33.20  20.62  3.78  0.76    2.02   25.58    NaN   
670827  36.00  71.00  2.20  30.80  18.20  3.67  0.58    1.77   26.15    NaN   
670828  15.75  63.00  1.02  28.90  16.00  3.80  0.49    0.75   15.82    NaN   
670829  15.00  66.00  0.40  26.85  14.05  5.20  0.59    2.10   17.05    NaN   

        col13  col14  col15  
0         0.0    0.0 

In [54]:
# categorical 변수를 mode로 채우기
idx_cat = df.dtypes=='object'
df_cat = df.loc[:,idx_cat]
print(df_cat)

                 col1              col2         col16
0           Ahmedabad   2015-01-01 1:00           NaN
1           Ahmedabad   2015-01-01 2:00           NaN
2           Ahmedabad   2015-01-01 3:00           NaN
3           Ahmedabad   2015-01-01 4:00           NaN
4           Ahmedabad   2015-01-01 5:00           NaN
...               ...               ...           ...
670825  Visakhapatnam  2020-06-30 20:00  Satisfactory
670826  Visakhapatnam  2020-06-30 21:00  Satisfactory
670827  Visakhapatnam  2020-06-30 22:00          Good
670828  Visakhapatnam  2020-06-30 23:00          Good
670829  Visakhapatnam   2020-07-01 0:00          Good

[670830 rows x 3 columns]


In [55]:
df_cat['col1'].value_counts()

Delhi                 48192
Mumbai                46728
Chennai               46728
Bengaluru             46728
Ahmedabad             46728
Lucknow               46728
Hyderabad             46643
Patna                 44554
Gurugram              38794
Visakhapatnam         35053
Amritsar              27805
Jorapokhar            26561
Jaipur                25241
Thiruvananthapuram    25187
Amaravati             22784
Brajrajnagar          21004
Talcher               20697
Kolkata               18039
Guwahati              12002
Chandigarh             7263
Shillong               5938
Bhopal                 5439
Kochi                  2390
Ernakulam              2388
Aizawl                 1216
Name: col1, dtype: int64

In [56]:
df_cat['col16'].value_counts()

Moderate        190884
Satisfactory    171473
Poor             66425
Very Poor        57448
Good             31863
Severe           27632
Name: col16, dtype: int64

In [57]:
df_cat.mode()

col1              col2     col16
0     Delhi  2020-03-11 10:00  Moderate
1       NaN  2020-03-11 11:00       NaN
2       NaN  2020-03-11 12:00       NaN
3       NaN  2020-03-11 13:00       NaN
4       NaN  2020-03-11 14:00       NaN
...     ...               ...       ...
1211    NaN   2020-04-30 6:00       NaN
1212    NaN   2020-04-30 7:00       NaN
1213    NaN   2020-04-30 8:00       NaN
1214    NaN   2020-04-30 9:00       NaN
1215    NaN   2020-05-01 0:00       NaN

[1216 rows x 3 columns]

In [58]:
cat_modes = df_cat.mode().iloc[0,:]
print(cat_modes)

col1                Delhi
col2     2020-03-11 10:00
col16            Moderate
Name: 0, dtype: object


In [59]:
df_cat.fillna(cat_modes)

col1              col2         col16
0           Ahmedabad   2015-01-01 1:00      Moderate
1           Ahmedabad   2015-01-01 2:00      Moderate
2           Ahmedabad   2015-01-01 3:00      Moderate
3           Ahmedabad   2015-01-01 4:00      Moderate
4           Ahmedabad   2015-01-01 5:00      Moderate
...               ...               ...           ...
670825  Visakhapatnam  2020-06-30 20:00  Satisfactory
670826  Visakhapatnam  2020-06-30 21:00  Satisfactory
670827  Visakhapatnam  2020-06-30 22:00          Good
670828  Visakhapatnam  2020-06-30 23:00          Good
670829  Visakhapatnam   2020-07-01 0:00          Good

[670830 rows x 3 columns]

#### 실습
* dataset_product.xlsx 데이터에서 다음에 따라 결측치를 처리하세요
* 1. object일 경우 mode로 처리
* 2. 연속형일 경우 평균으로 처리

In [60]:
df2 =  pd.read_excel('./Dataset/dataset_product.xlsx')

In [61]:
df2.dtypes

col1       object
col2       object
col3       object
col4       object
col5       object
           ...   
col599      int64
col600    float64
col601     object
col602     object
col603    float64
Length: 603, dtype: object

In [62]:
idx_col1 = df2.dtypes=='object'
idx_col2 = df2.dtypes=='float64'

In [64]:
df2_cat = df2.loc[:,idx_col1]
df2_contin = df2.loc[:,idx_col2]

In [65]:
df2_cat

col1 col2 col3 col4   col5        col6         col8        col9  \
0     SB63856  생산량  11월  4분기  2019년   HBU096890  V77065L3XX1  HTSCC77HA1   
1     SB63856  생산량  11월  4분기  2019년   HBU096880  V77065L3XX1  HTSCC77HA1   
2     SB64098  생산량  10월  4분기  2019년  HBU114310A  V62078F5CR1  HTSCC62GA2   
3     SB64098  생산량  10월  4분기  2019년   HBU114310  V62078F5CR1  HTSCC62GA2   
4     SB64406  생산량  10월  4분기  2019년   HBU140120  V77040L5CR2  HTSCC77GA2   
...       ...  ...  ...  ...    ...         ...          ...         ...   
7074  SB84666  생산량  03월  1분기  2020년  HBC098990A  VA5040L3CR1  HTSCCA5HA2   
7075  SB84666  생산량  03월  1분기  2020년   HBC098940  VA5040L3CR1  HTSCCA5HA2   
7076  SB84666  생산량  03월  1분기  2020년   HBC098560  VA5040L3CR1  HTSCCA5HA2   
7077  SB84666  생산량  03월  1분기  2020년   HBC098910  VA5040L3CR1  HTSCCA5HA2   
7078  SB84666  생산량  03월  1분기  2020년   HBC098990  VA5040L3CR1  HTSCCA5HA2   

                col15 col16  ...  col575     col578  \
0     FFHD000000019GG   FHD  ...  C≥0.7%  경유C목표≥0.5   
1     FFHD000000019GG   FHD  ...  C≥0.7%  경유C목표≥0.5   
2     FFHD000000018JU   FHD  ...  C≥0.35  경유C목표≥0.5   
3     FFHD000000018JV   FHD  ...  C≥0.35  경유C목표≥0.5   
4     FFHD00000001MMT   FHD  ...  C≥0.7%  경유C목표≥0.5   
...               ...   ...  ...     ...        ...   
7074  FFHD000000015FK   FHD  ...  C≥0.7%  경유C목표≥0.8   
7075  FFHD000000015FK   FHD  ...  C≥0.7%  경유C목표≥0.8   
7076  FFHD000000015FK   FHD  ...  C≥0.7%  경유C목표≥0.8   
7077  FFHD000000015FK   FHD  ...  C≥0.7%  경유C목표≥0.8   
7078  FFHD000000015FK   FHD  ...  C≥0.7%  경유C목표≥0.8   

                            col583 col590    col593    col594    col595  \
0     2차정련코드=NULL or 두번째코드=1(A1제외)      6  02:02:50  02:02:59  02:03:51   
1     2차정련코드=NULL or 두번째코드=1(A1제외)      6  02:02:50  02:02:59  02:03:51   
2     2차정련코드=NULL or 두번째코드=1(A1제외)      7  19:15:20  19:15:30  19:16:22   
3     2차정련코드=NULL or 두번째코드=1(A1제외)      7  19:15:20  19:15:30  19:16:22   
4     2차정련코드=NULL or 두번째코드=1(A1제외)      8  19:55:26  19:55:39  19:56:08   
...                            ...    ...       ...       ...       ...   
7074  2차정련코드=NULL or 두번째코드=1(A1제외)      6  09:27:59  09:28:16       NaN   
7075  2차정련코드=NULL or 두번째코드=1(A1제외)      6  09:27:59  09:28:16       NaN   
7076  2차정련코드=NULL or 두번째코드=1(A1제외)      6  09:27:59  09:28:16       NaN   
7077  2차정련코드=NULL or 두번째코드=1(A1제외)      6  09:27:59  09:28:16       NaN   
7078  2차정련코드=NULL or 두번째코드=1(A1제외)      6  09:27:59  09:28:16       NaN   

        col596 col601 col602  
0     02:03:36    NaN    NaN  
1     02:03:36    NaN    NaN  
2     19:15:52      Y      Y  
3     19:15:52      Y      Y  
4          NaN    NaN    NaN  
...        ...    ...    ...  
7074  09:28:40    NaN    NaN  
7075  09:28:40    NaN    NaN  
7076  09:28:40    NaN    NaN  
7077  09:28:40    NaN    NaN  
7078  09:28:40    NaN    NaN  

[7079 rows x 100 columns]

In [66]:
df2_cat_modes = df2_cat.mode().iloc[0,:]
df2_cat_fill = df2_cat.fillna(df2_cat_modes)
df2_contin_fill = df2_contin.fillna(df2_contin.mean())
# RE2_fill = RE2.fillna(RE2.mode())
# RE3_fill = RE3.fillna(RE3.mean())

In [67]:
df2_fill = pd.concat([df2_cat_fill, df2_contin_fill], axis=1)

In [68]:
print(df2_fill)

         col1 col2 col3 col4   col5        col6         col8        col9  \
0     SB63856  생산량  11월  4분기  2019년   HBU096890  V77065L3XX1  HTSCC77HA1   
1     SB63856  생산량  11월  4분기  2019년   HBU096880  V77065L3XX1  HTSCC77HA1   
2     SB64098  생산량  10월  4분기  2019년  HBU114310A  V62078F5CR1  HTSCC62GA2   
3     SB64098  생산량  10월  4분기  2019년   HBU114310  V62078F5CR1  HTSCC62GA2   
4     SB64406  생산량  10월  4분기  2019년   HBU140120  V77040L5CR2  HTSCC77GA2   
...       ...  ...  ...  ...    ...         ...          ...         ...   
7074  SB84666  생산량  03월  1분기  2020년  HBC098990A  VA5040L3CR1  HTSCCA5HA2   
7075  SB84666  생산량  03월  1분기  2020년   HBC098940  VA5040L3CR1  HTSCCA5HA2   
7076  SB84666  생산량  03월  1분기  2020년   HBC098560  VA5040L3CR1  HTSCCA5HA2   
7077  SB84666  생산량  03월  1분기  2020년   HBC098910  VA5040L3CR1  HTSCCA5HA2   
7078  SB84666  생산량  03월  1분기  2020년   HBC098990  VA5040L3CR1  HTSCCA5HA2   

                col15 col16  ... col579 col580 col581 col582 col586 col589  \
0     FFH

### 3. Numpy

###  3.1 행렬 살펴보기

In [69]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [70]:
#df_np = df.to_numpy()
df_np= df.values

In [71]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [72]:
df_np

array([['Ahmedabad', '2015-01-01 1:00', nan, ..., 0.0, nan, nan],
       ['Ahmedabad', '2015-01-01 2:00', nan, ..., 0.0, nan, nan],
       ['Ahmedabad', '2015-01-01 3:00', nan, ..., 0.0, nan, nan],
       ...,
       ['Visakhapatnam', '2020-06-30 22:00', 36.0, ..., nan, 50.0,
        'Good'],
       ['Visakhapatnam', '2020-06-30 23:00', 15.75, ..., nan, 50.0,
        'Good'],
       ['Visakhapatnam', '2020-07-01 0:00', 15.0, ..., nan, 50.0, 'Good']],
      dtype=object)

In [73]:
type(df_np)

numpy.ndarray

In [74]:
# 행렬의 크기
df_np.shape

(670830, 16)

In [75]:
# 변수의 형태
df_np.dtype

dtype('O')

In [76]:
df_contin_np = df_contin.values

In [77]:
print(df_contin_np)

[[      nan       nan 1.000e+00 ... 0.000e+00 0.000e+00       nan]
 [      nan       nan 2.000e-02 ... 0.000e+00 0.000e+00       nan]
 [      nan       nan 8.000e-02 ... 0.000e+00 0.000e+00       nan]
 ...
 [3.600e+01 7.100e+01 2.200e+00 ...       nan       nan 5.000e+01]
 [1.575e+01 6.300e+01 1.020e+00 ...       nan       nan 5.000e+01]
 [1.500e+01 6.600e+01 4.000e-01 ...       nan       nan 5.000e+01]]


In [78]:
df_contin_np.dtype

dtype('float64')

In [79]:
df_contin_np.shape

(670830, 13)

In [80]:
df_contin_np

array([[      nan,       nan, 1.000e+00, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 2.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 8.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       ...,
       [3.600e+01, 7.100e+01, 2.200e+00, ...,       nan,       nan,
        5.000e+01],
       [1.575e+01, 6.300e+01, 1.020e+00, ...,       nan,       nan,
        5.000e+01],
       [1.500e+01, 6.600e+01, 4.000e-01, ...,       nan,       nan,
        5.000e+01]])

In [81]:
df_contin_np[0,2]

1.0

In [82]:
df_contin_np[0,:5]

array([  nan,   nan,  1.  , 40.01, 36.37])

In [83]:
df_cat_np = df_cat.values

In [84]:
df_cat_np

array([['Ahmedabad', '2015-01-01 1:00', nan],
       ['Ahmedabad', '2015-01-01 2:00', nan],
       ['Ahmedabad', '2015-01-01 3:00', nan],
       ...,
       ['Visakhapatnam', '2020-06-30 22:00', 'Good'],
       ['Visakhapatnam', '2020-06-30 23:00', 'Good'],
       ['Visakhapatnam', '2020-07-01 0:00', 'Good']], dtype=object)

### 3.2 조건에 맞는 행이나 열 선택,  최대, 최소, 행렬 붙이기,

In [85]:
df_contin_np

array([[      nan,       nan, 1.000e+00, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 2.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 8.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       ...,
       [3.600e+01, 7.100e+01, 2.200e+00, ...,       nan,       nan,
        5.000e+01],
       [1.575e+01, 6.300e+01, 1.020e+00, ...,       nan,       nan,
        5.000e+01],
       [1.500e+01, 6.600e+01, 4.000e-01, ...,       nan,       nan,
        5.000e+01]])

In [86]:
df_contin_np[:,1]

array([nan, nan, nan, ..., 71., 63., 66.])

In [87]:
# 첫번째 열이 2 이상인 행 선택
idx7 = df_contin_np[:,1]>=2

In [88]:
idx7

array([False, False, False, ...,  True,  True,  True])

In [89]:
idx_col1.array

<PandasArray>
[ True,  True,  True,  True,  True,  True, False,  True,  True, False,
 ...
  True,  True,  True, False, False, False, False,  True,  True, False]
Length: 603, dtype: bool

In [90]:
type(idx_col1.array)

pandas.core.arrays.numpy_.PandasArray

In [91]:
type(idx7)

numpy.ndarray

In [92]:
idx7

array([False, False, False, ...,  True,  True,  True])

In [93]:
df_contin_np[idx7,:]

array([[ 40.02, 120.06,  13.87, ...,  85.05,  13.26,    nan],
       [ 39.29, 108.41,  17.95, ...,  84.22,  16.41,    nan],
       [ 57.52, 153.03,  18.01, ...,  83.48,  10.64,    nan],
       ...,
       [ 36.  ,  71.  ,   2.2 , ...,    nan,    nan,  50.  ],
       [ 15.75,  63.  ,   1.02, ...,    nan,    nan,  50.  ],
       [ 15.  ,  66.  ,   0.4 , ...,    nan,    nan,  50.  ]])

In [94]:
df_contin_np.mean()

nan

In [95]:
print('전체 평균:',df_contin_np.mean()) # 전체 평균 출력
print('각 열별 평균:',df_contin_np.mean(0)) # 각 열별 평균 출력
print('각 행별 평균:',df_contin_np.mean(1))


전체 평균: nan
각 열별 평균: [nan nan nan nan nan nan nan nan nan nan nan nan nan]
각 행별 평균: [nan nan nan ... nan nan nan]


In [96]:
print('전체 최소:',df_contin_np.min()) # 전체 평균 출력
print('각 열별 최소',df_contin_np.min(0)) # 각 열별 평균 출력
print('각 행별 최소:',df_contin_np.min(1))


전체 최소: nan
각 열별 최소 [nan nan nan nan nan nan nan nan nan nan nan nan nan]
각 행별 최소: [nan nan nan ... nan nan nan]


In [97]:
# nan 무시
print('전체 평균(nan무시):',np.nanmean(df_contin_np)) # 전체 평균 출력
print('각 열별 평균(nan 무시):',np.nanmean(df_contin_np,0)) # 각 열별 평균 출력
print('각 행별 평균(nan 무시):',np.nanmean(df_contin_np,1))


전체 평균(nan무시): 41.56496389319007
각 열별 평균(nan 무시): [ 70.06736366 124.03702445  17.81342348  29.58927888  32.95796941
  24.2683775    2.26577333  14.31224418  34.8079538    3.12731016
   8.92342244   3.14677558 171.58733611]
각 행별 평균(nan 무시): [25.05625 16.6775  10.42375 ... 24.037   19.553   19.724  ]


In [98]:
# nan 무시
print('전체 최소(nan무시):',np.nanmin(df_contin_np)) # 전체 평균 출력
print('각 열별 최소(nan 무시):',np.nanmin(df_contin_np,0)) # 각 열별 평균 출력
print('각 행별 최소(nan 무시):',np.nanmin(df_contin_np,1))


전체 최소(nan무시): 0.0
각 열별 최소(nan 무시): [0.01 0.01 0.01 0.01 0.   0.01 0.   0.01 0.01 0.   0.   0.   9.  ]
각 행별 최소(nan 무시): [0.   0.   0.   ... 0.58 0.49 0.4 ]


#### 실습
 전체, 각 열별, 각 행별 최대, 평균과 표준편차 (nan 무시)

In [99]:
df_contin_np

array([[      nan,       nan, 1.000e+00, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 2.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 8.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       ...,
       [3.600e+01, 7.100e+01, 2.200e+00, ...,       nan,       nan,
        5.000e+01],
       [1.575e+01, 6.300e+01, 1.020e+00, ...,       nan,       nan,
        5.000e+01],
       [1.500e+01, 6.600e+01, 4.000e-01, ...,       nan,       nan,
        5.000e+01]])

In [100]:
# nan 무시
print('전체 표준편차(nan무시):',np.nanstd(df_contin_np)) # 전체 평균 출력
print('각 열별 표준편차(nan 무시):',np.nanstd(df_contin_np,0)) # 각 열별 평균 출력
print('각 행별 표준편차(nan 무시):',np.nanstd(df_contin_np,1))


전체 표준편차(nan무시): 80.32559358418293
각 열별 표준편차(nan 무시): [ 76.08449633 105.66332903  32.70245826  29.59343591  40.53685208
  29.54583117  11.28662937  19.78878223  29.93055326  16.52523779
  21.94807375   7.94475527 165.26175092]
각 행별 표준편차(nan 무시): [40.0064629  28.09144476 17.38466993 ... 22.46042522 20.61948062
 21.05142237]


In [101]:
# nan 무시
print('전체 최대(nan무시):',np.nanmax(df_contin_np)) # 전체 평균 출력
print('각 열별 최대(nan 무시):',np.nanmax(df_contin_np,0)) # 각 열별 평균 출력
print('각 행별 최대(nan 무시):',np.nanmax(df_contin_np,1))


전체 최대(nan무시): 3133.0
각 열별 최대(nan 무시): [ 999.99 1000.    499.99  499.51  498.61  499.97  498.57  199.96  497.62
  498.07  499.4   499.99 3133.  ]
각 행별 최대(nan 무시): [122.07  85.9   52.83 ...  71.    63.    66.  ]


In [102]:
# 두 행렬을 세로로 이어 붙이기

df_np1 = df_contin_np[:3,:5]
df_np2 = df_contin_np[3:6,:5]


In [103]:
print(df_np1)
print(df_np1.shape)

[[      nan       nan 1.000e+00 4.001e+01 3.637e+01]
 [      nan       nan 2.000e-02 2.775e+01 1.973e+01]
 [      nan       nan 8.000e-02 1.932e+01 1.108e+01]]
(3, 5)


In [104]:
print(df_np2)
print(df_np2.shape)

[[  nan   nan  0.3  16.45  9.2 ]
 [  nan   nan  0.12 14.9   7.85]
 [  nan   nan  0.33 15.95 10.82]]
(3, 5)


In [105]:
df_np3=np.concatenate((df_np1,df_np2))
print(df_np3)
print(df_np3.shape)

[[      nan       nan 1.000e+00 4.001e+01 3.637e+01]
 [      nan       nan 2.000e-02 2.775e+01 1.973e+01]
 [      nan       nan 8.000e-02 1.932e+01 1.108e+01]
 [      nan       nan 3.000e-01 1.645e+01 9.200e+00]
 [      nan       nan 1.200e-01 1.490e+01 7.850e+00]
 [      nan       nan 3.300e-01 1.595e+01 1.082e+01]]
(6, 5)


In [106]:
# 두 행렬을 가로로 이어 붙이기
df_np4=np.concatenate((df_np1,df_np2), axis=1)
print(df_np4)
print(df_np4.shape)

[[      nan       nan 1.000e+00 4.001e+01 3.637e+01       nan       nan
  3.000e-01 1.645e+01 9.200e+00]
 [      nan       nan 2.000e-02 2.775e+01 1.973e+01       nan       nan
  1.200e-01 1.490e+01 7.850e+00]
 [      nan       nan 8.000e-02 1.932e+01 1.108e+01       nan       nan
  3.300e-01 1.595e+01 1.082e+01]]
(3, 10)


## 4. Impute

### 4.1 결측치 처리하기

In [107]:
# 결측치 확인하기
idx_missing=np.isnan(df_contin_np)
print(idx_missing)

[[ True  True False ... False False  True]
 [ True  True False ... False False  True]
 [ True  True False ... False False  True]
 ...
 [False False False ...  True  True False]
 [False False False ...  True  True False]
 [False False False ...  True  True False]]


In [108]:
print('전체 결측치의 개수:', np.isnan(df_contin_np).sum())
print('행별 결측치의 개수:', np.isnan(df_contin_np).sum(1))
print('열별 결측치의 개수:', np.isnan(df_contin_np).sum(0))

전체 결측치의 개수: 2290978
행별 결측치의 개수: [5 5 5 ... 3 3 3]
열별 결측치의 개수: [139972 289899 112205 112895 119336 263630  84432 126939 123458 155246
 210532 427329 125105]


In [98]:
df_contin_np.shape

(670830, 13)

In [99]:
# sklearn.impute에서 모두 불러오기
from sklearn.impute import *
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

In [100]:
?SimpleImputer

In [101]:
# 평균으로 채워넣기
imp_mean = SimpleImputer(strategy='mean', missing_values=np.nan) 
# 1. 모형 선언,  결측치는 평균으로 채워넣고 결측치는 np.nan 값을 가지고
imp_mean.fit(df_contin_np)
# 2. 각 열별 평균을 EQ_contin_np 행렬을 기준으로 계산

SimpleImputer()

In [102]:
# 각 열의 fit된 평균값 출력
imp_mean.statistics_

array([ 70.06736366, 124.03702445,  17.81342348,  29.58927888,
        32.95796941,  24.2683775 ,   2.26577333,  14.31224418,
        34.8079538 ,   3.12731016,   8.92342244,   3.14677558,
       171.58733611])

In [103]:
# 3. transform : statistics_에 저장된 값으로 결측치를 채워 넣겠다. 
print(imp_mean.transform(df_contin_np))

[[7.00673637e+01 1.24037024e+02 1.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.71587336e+02]
 [7.00673637e+01 1.24037024e+02 2.00000000e-02 ... 0.00000000e+00
  0.00000000e+00 1.71587336e+02]
 [7.00673637e+01 1.24037024e+02 8.00000000e-02 ... 0.00000000e+00
  0.00000000e+00 1.71587336e+02]
 ...
 [3.60000000e+01 7.10000000e+01 2.20000000e+00 ... 8.92342244e+00
  3.14677558e+00 5.00000000e+01]
 [1.57500000e+01 6.30000000e+01 1.02000000e+00 ... 8.92342244e+00
  3.14677558e+00 5.00000000e+01]
 [1.50000000e+01 6.60000000e+01 4.00000000e-01 ... 8.92342244e+00
  3.14677558e+00 5.00000000e+01]]


In [104]:
# median으로 채워넣기
imp_median = SimpleImputer(strategy='median', missing_values=np.nan) # 선언, median으로 결측치를 채워 넣겠다
imp_median.fit(df_contin_np) # median 값을 학습

SimpleImputer(strategy='median')

In [105]:
imp_median.statistics_

array([ 48.5 ,  94.89,   8.08,  21.  ,  21.24,  15.9 ,   0.81,   8.4 ,
        26.18,   0.92,   2.77,   0.78, 120.  ])

In [106]:
print(imp_median.transform(df_contin_np))

[[4.850e+01 9.489e+01 1.000e+00 ... 0.000e+00 0.000e+00 1.200e+02]
 [4.850e+01 9.489e+01 2.000e-02 ... 0.000e+00 0.000e+00 1.200e+02]
 [4.850e+01 9.489e+01 8.000e-02 ... 0.000e+00 0.000e+00 1.200e+02]
 ...
 [3.600e+01 7.100e+01 2.200e+00 ... 2.770e+00 7.800e-01 5.000e+01]
 [1.575e+01 6.300e+01 1.020e+00 ... 2.770e+00 7.800e-01 5.000e+01]
 [1.500e+01 6.600e+01 4.000e-01 ... 2.770e+00 7.800e-01 5.000e+01]]


In [107]:
df_contin.shape

(670830, 13)

In [108]:
?KNNImputer

In [109]:
df_contin_np2 = df_contin.sample(10000).to_numpy()

In [110]:
# knn으로 채워넣기
imp_KNN = KNNImputer(n_neighbors=5, missing_values=np.nan)
imp_KNN.fit(df_contin_np2)
print(imp_KNN.transform(df_contin_np2))

[[5.9000e+01 8.8474e+01 8.6800e+00 ... 1.2960e+01 9.0100e+00 1.5300e+02]
 [4.3560e+01 1.1219e+02 5.2900e+00 ... 6.4100e+00 2.1000e-01 7.2000e+01]
 [4.3250e+01 5.8412e+01 1.2260e+01 ... 1.8920e+01 1.6230e+01 8.0000e+01]
 ...
 [3.5380e+01 1.2218e+02 2.0170e+01 ... 1.1600e-01 1.4000e-02 3.1900e+02]
 [7.4850e+01 1.2279e+02 1.2330e+01 ... 1.0540e+01 4.9000e-01 1.8100e+02]
 [4.3020e+01 6.7274e+01 2.6320e+01 ... 1.2000e+01 1.2400e-01 9.2000e+01]]


In [111]:
?IterativeImputer

In [112]:
# IterativeImputer를 이용해서  채워넣기
imp_mice = IterativeImputer(missing_values=np.nan)
imp_mice.fit(df_contin_np2)
print(imp_mice.transform(df_contin_np2))

[[5.90000000e+01 1.17936753e+02 8.68000000e+00 ... 1.29600000e+01
  9.01000000e+00 1.53000000e+02]
 [4.35600000e+01 1.12190000e+02 5.29000000e+00 ... 6.41000000e+00
  2.10000000e-01 7.20000000e+01]
 [4.32500000e+01 9.70373189e+01 1.22600000e+01 ... 1.89200000e+01
  1.62300000e+01 8.00000000e+01]
 ...
 [3.53800000e+01 1.22180000e+02 2.01700000e+01 ... 2.65866469e+01
  5.05494868e+00 3.19000000e+02]
 [7.48500000e+01 1.22790000e+02 1.23300000e+01 ... 1.05400000e+01
  4.90000000e-01 1.81000000e+02]
 [4.30200000e+01 9.46012059e+01 2.63200000e+01 ... 1.20000000e+01
  5.64943327e+00 9.20000000e+01]]


#### 실습

In [113]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [114]:
df_contin_np2

array([[5.9000e+01,        nan, 8.6800e+00, ..., 1.2960e+01, 9.0100e+00,
        1.5300e+02],
       [4.3560e+01, 1.1219e+02, 5.2900e+00, ..., 6.4100e+00, 2.1000e-01,
        7.2000e+01],
       [4.3250e+01,        nan, 1.2260e+01, ..., 1.8920e+01, 1.6230e+01,
        8.0000e+01],
       ...,
       [3.5380e+01, 1.2218e+02, 2.0170e+01, ...,        nan,        nan,
        3.1900e+02],
       [7.4850e+01, 1.2279e+02, 1.2330e+01, ..., 1.0540e+01, 4.9000e-01,
        1.8100e+02],
       [4.3020e+01,        nan, 2.6320e+01, ..., 1.2000e+01,        nan,
        9.2000e+01]])